# Config file for simCLR training with views that share both background and digit features.

# ImageNet info
imagenet_data_folder: /home/howk/Documents/Professionel_études/AgroParisTech_cours/3A_IODAA/code_folder/Projet_romain/data_td3/subset_imagenet
imagenet_labels_file: /home/howk/Documents/Professionel_études/AgroParisTech_cours/3A_IODAA/code_folder/Projet_romain/data_td3/imagenet_labels.txt
imagenet_classes: [2, 3, 4, 6, 43, 203, 400, 600, 700, 800]

# MNIST info
mnist_data_folder:

# Model info
d_model: 128

# Data info
shared_feature: ['background', 'digit']
transforms:
  - random_cropping
  - resize
  - gaussian_blur
  - normalize
img_size: 224
crop_size: 128
kernel_size: 11
data_mean: [0.485, 0.456, 0.406]
data_std: [0.229, 0.224, 0.225]

# Training info
epochs: 100
batch_size: 8
lr: 0.00035
temperature: 0.1
device: 'cuda'

# Pretrained parameters
pretrained_params: /home/howk/Documents/Professionel_études/AgroParisTech_cours/3A_IODAA/code_folder/Projet_romain/data_td3/pretrained_alexnet_dc.tar

# Results folder
res_dir:
